SeriesGuide/src/main/java/com/battlelancer/seriesguide/ui/OverviewActivity.java

DBUtils.getShow can return [null](https://github.com/UweTrottmann/SeriesGuide/blob/master/SeriesGuide/src/main/java/com/battlelancer/seriesguide/util/DBUtils.java#L391) and its return value is checked for null in other [places](https://github.com/UweTrottmann/SeriesGuide/blob/1596acfc4e59953eddb974270567306d2fec7bc2/SeriesGuide/src/main/java/com/battlelancer/seriesguide/ui/EpisodesActivity.java#L164) where the method is called. This pull request fixes a possible NPE on an call to DBUtils.getShow where the return value is not checked for null before dereferencing.
Just to be clear, I identified this bug using a static analysis [tool](https://github.com/cuplv/hopper) that I have been developing and have not attempted to reproduce this issue while running the app.

Fixing possible NPE in OverviewActivity.launchSearch

---

SeriesGuide/src/main/java/com/battlelancer/seriesguide/ui/ActivityFragment.java
SeriesGuide/src/main/java/com/battlelancer/seriesguide/ui/EpisodeDetailsFragment.java
SeriesGuide/src/main/java/com/battlelancer/seriesguide/ui/OverviewFragment.java
SeriesGuide/src/main/java/com/battlelancer/seriesguide/ui/QuickCheckInActivity.java

CheckinDialogFragment.newInstance can return [null](https://github.com/UweTrottmann/SeriesGuide/blob/2662ddd061f9c74df9b72451e6005ae02d2fb6b4/SeriesGuide/src/main/java/com/battlelancer/seriesguide/ui/dialogs/CheckInDialogFragment.java#L40), but its return value is dereferenced without checked in several places. This pull request adds null checks in each place where this method is called.
Like #449, this bug was identified using a static analysis tool that I have been developing and I have not attempted to reproduce this issue while running the app.

Fixing possible NPEs when CheckInDialogFragment.newInstance returns null

---

SeriesGuide/src/main/java/com/battlelancer/seriesguide/util/ShortcutUtils.java
SeriesGuide/src/main/res/values/dimens.xml

This change removes the old shortcut icon size in favor of a more poster friendly size while also applying a nice round effect to the icons.
I basically just swapped the shortcut icon dimens with the poster dimens. I noticed that the poster dimens vary across a few densities, but there are actually only two variations. So, I'm not sure if you'd rather create a unique icon size for the shortcuts or just continue using the poster size. I mean:
**show_poster_width/height** is in:
* values/
* values-xlarge/
* values-xlarge-land/
* values-sw720dp/
But the sames dimens are used in all of the fancy values folder. So, maybe those could be cleaned up?
[The inspiration for it comes from this G+ post from this morning.](https://plus.google.com/+PavelAzroyan/posts/UiWpyCH52wT) Personally, I like the …

Use a more poster friendly shortcut icon size

---

SeriesGuide/src/main/AndroidManifest.xml

This is done because extension applications can open extension configuration Activity to guide users.

`ExtensionsConfigurationActivity` is exported.

---

SeriesGuide/src/main/java/com/battlelancer/seriesguide/adapters/MoviesAdapter.java
SeriesGuide/src/main/java/com/battlelancer/seriesguide/adapters/MoviesCursorAdapter.java
SeriesGuide/src/main/java/com/battlelancer/seriesguide/adapters/PeopleAdapter.java
SeriesGuide/src/main/java/com/battlelancer/seriesguide/ui/MoviesActivity.java

These commits fix 2 issues with the poster shared element transitions:
1) The adapter position is replaced with a stable id for the transition name. This allows to match the correct poster even if the items have changed position after the activity has been re-created.
2) When MoviesActivity is re-created, the transition is postponed until after the next layout pass. This gives a chance to the adapters to repopulate the posters, since adapter population is asynchronous. Thanks to this, the poster animation will also work properly after changing the orientation in the details page then navigating back to MoviesActivity, which doesn't work currently.

Shared element transitions improvements

---

app/schemas/com.battlelancer.seriesguide.provider.SgRoomDatabase/46.json
app/src/androidTest/java/com/battlelancer/seriesguide/provider/MigrationTest.java
app/src/androidTest/java/com/battlelancer/seriesguide/provider/RoomDatabaseTestHelper.java
app/src/androidTest/java/com/battlelancer/seriesguide/provider/SqliteDatabaseTestHelper.java
app/src/main/java/com/battlelancer/seriesguide/dataliberation/JsonExportTask.java
app/src/main/java/com/battlelancer/seriesguide/dataliberation/model/Show.java
app/src/main/java/com/battlelancer/seriesguide/model/SgShow.java
app/src/main/java/com/battlelancer/seriesguide/provider/SeriesGuideContract.java
app/src/main/java/com/battlelancer/seriesguide/provider/SgRoomDatabase.kt
app/src/main/java/com/battlelancer/seriesguide/thetvdbapi/TvdbLinks.kt
app/src/main/java/com/battlelancer/seriesguide/thetvdbapi/TvdbTools.java
app/src/main/java/com/battlelancer/seriesguide/ui/episodes/EpisodeDetailsFragment.java
app/src/main/java/com/battlelancer/seriesguide/ui/overview/OverviewFragment.java
app/src/main/java/com/battlelancer/seriesguide/ui/overview/ShowFragment.java
app/src/main/java/com/battlelancer/seriesguide/util/ShareUtils.java
build.gradle

Links to TVDB from within the app use the new format. See #545.
However, sharing a TVDB link to SeriesGuide to add a show still won't work as the API has no way to get a TVDB id from a slug. See #546.

Support TVDB slug for links

---

app/src/main/java/com/battlelancer/seriesguide/settings/DisplaySettings.java
app/src/main/java/com/battlelancer/seriesguide/thetvdbapi/TvdbImageTools.java
app/src/main/java/com/battlelancer/seriesguide/thetvdbapi/TvdbTools.java
app/src/main/java/com/battlelancer/seriesguide/ui/SearchActivity.java
app/src/main/java/com/battlelancer/seriesguide/ui/SeriesGuidePreferences.java
app/src/main/java/com/battlelancer/seriesguide/ui/ShowsActivity.java
app/src/main/java/com/battlelancer/seriesguide/ui/dialogs/LanguageChoiceDialogFragment.java
app/src/main/java/com/battlelancer/seriesguide/ui/search/AddShowDialogFragment.java
app/src/main/java/com/battlelancer/seriesguide/ui/search/ShowsDiscoverFragment.kt
app/src/main/java/com/battlelancer/seriesguide/ui/search/TraktAddFragment.java
app/src/main/java/com/battlelancer/seriesguide/ui/search/TraktAddLoader.java
app/src/main/java/com/battlelancer/seriesguide/ui/search/TvdbShowLoader.java
app/src/main/java/com/battlelancer/seriesguide/ui/shows/ShowsNowFragment.java
app/src/main/java/com/battlelancer/seriesguide/ui/shows/TraktFriendsEpisodeHistoryLoader.java
app/src/main/java/com/battlelancer/seriesguide/ui/shows/TraktRecentEpisodeHistoryLoader.java
app/src/main/java/com/battlelancer/seriesguide/ui/streams/EpisodeHistoryAdapter.java
app/src/main/java/com/battlelancer/seriesguide/ui/streams/UserEpisodeStreamFragment.java
app/src/main/java/com/battlelancer/seriesguide/util/LanguageTools.java
app/src/main/java/com/battlelancer/seriesguide/util/SgPicassoRequestHandler.java
app/src/main/res/layout/dialog_addshow.xml
app/src/main/res/xml/settings_basic.xml

- Ensures consistent behavior across devices and encourages users to set a language.
- Use search or fallback language in any case a show is added.

Drop default language setting, default to English

---

api/src/main/java/android/support/v4/app/SafeJobIntentService.java
api/src/main/java/com/battlelancer/seriesguide/api/SeriesGuideExtension.java
app/src/main/java/com/battlelancer/seriesguide/extensions/ExtensionActionService.java
app/src/main/java/com/battlelancer/seriesguide/ui/overview/UnwatchedUpdaterService.java

Add SafeJobIntentService which actually stops de-queuing work after the
associated job was stopped by using SafeCommandProcessor
following the example implementation of Dianne Hackborn.
https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/app/JobWorkService.java
https://issuetracker.google.com/issues/63622293

Potential fix for JobIntentService SecurityException de-queuing work

---

app/src/main/java/com/battlelancer/seriesguide/provider/SeriesGuideProvider.java
app/src/main/java/com/battlelancer/seriesguide/provider/SgRoomDatabase.kt

The Room invalidation tracker requires transactions to be handled
through the RoomDatabase API (this is also suggested by [the Content
Provider example](https://github.com/googlesamples/android-architecture-components/blob/master/PersistenceContentProviderSample/app/src/main/java/com/example/android/contentprovidersample/provider/SampleContentProvider.java)). Also temporarily disable yielding as not sure if that
throws of the invalidation tracking.
And temporarily allow main thread queries.
Some ContentProvider ops in SeriesGuide do run on the main thread.
Allow them until they are moved to background threads.

Use Room transactions in Content Provider

---

api/src/main/java/android/support/v4/app/SafeJobIntentService.java

Issue #575
The previous fix (#574) was pointless (at least with support library 28.0.0, looks like AndroidX 1.0.0 release has no changes as well) as `JobServiceEngineImpl.dequeueWork()` checks if `JobParameters mParams` are `null`, which is the case if the job was stopped (and the processor cancelled).
Now, explicitly stop de-queuing work if the service is to be destroyed.
Calling `onStopJob()` in `JobIntentService.onDestroy()` works as it sets `JobServiceEngineImpl` `JobParameters mParams` to `null` and cancels the processor. Both `JobServiceEngineImpl.dequeueWork()` and `WrapperWorkItem.completeWork()` check for null before calling the crashing methods.
If this won't stick, will have to resort to try+catch.

Safe JobIntentService 2

---

app/src/main/java/com/battlelancer/seriesguide/thetvdbapi/TvdbImageTools.kt
app/src/test/java/com/battlelancer/seriesguide/thetvdbapi/TvdbImageToolsTest.kt

Should save a redirect from www->artworks (theoratically, right now there is none).
However, wait until merging as this new subdomain does not seem capable of serving the old `_cache` subpath for thumbnails, but only the new `_t` suffix on poster file names.

Use new artworks.thetvdb.com base for images

---

app/src/androidTest/java/com/battlelancer/seriesguide/provider/MigrationTest.java
app/src/main/java/com/battlelancer/seriesguide/dataliberation/JsonImportTask.java
app/src/main/java/com/battlelancer/seriesguide/thetvdbapi/TvdbImageTools.kt
app/src/test/java/com/battlelancer/seriesguide/thetvdbapi/TvdbImageToolsTest.kt

Using the new artworks URL with a legacy cache path directly does not work.
So use the www subdomain if a poster path uses the legacy `_cache` path. TVDB has redirects set up that correctly rewrite the URL to the artworks subdomain and `_t` file name suffix.
E.g. `https://www.thetvdb.com/banners/_cache/posters/example.jpg` redirects to `https://artworks.thetvdb.com/banners/posters/example_t.jpg`.
Also update JSON importer to create missing poster thumbnail paths using new file name postfix instead of legacy cache path.

Support image URLs with legacy cache path

---

app/src/main/java/com/battlelancer/seriesguide/dataliberation/JsonExportTask.java

Closes https://github.com/UweTrottmann/SeriesGuide/issues/719
Taken from #718 to ensure it makes it to the upcoming release.

Truncate Storage Access Framework file before writing backup to it.

---

app/src/main/java/com/battlelancer/seriesguide/provider/MovieHelper.java
app/src/main/java/com/battlelancer/seriesguide/provider/SeriesGuideContract.java
app/src/main/java/com/battlelancer/seriesguide/sync/HexagonMovieSync.kt
app/src/main/java/com/battlelancer/seriesguide/sync/TraktMovieSync.java

Right now, for whatever reason, when connecting Trakt movies that are watched on the device are cleared and replaced by whatever movies are watched on Trakt. This is not desired, instead they should be uploaded.

Merge watched movies with Trakt

---

CREDITS.txt
app/build.gradle
app/src/main/java/com/battlelancer/seriesguide/SgApp.kt
app/src/main/java/com/battlelancer/seriesguide/ui/BaseTopActivity.java
app/src/main/java/com/battlelancer/seriesguide/util/Errors.kt

Try to get reports by error code so it's easier to share feedback to Trakt about what's going wrong. This is harder to do on Crashlytics, so hopefully running a Countly instance is better.
- Records ~IP address~ (can turn off Request Logs plugin!), anonymous installation identifier, device model and Android version.
- Data kept for at most 90 days.

Use Countly to report some network request errors.

---

CONTRIBUTING.md

As TheTVDB was removed from release 58, for contribution an API key for TheTVDB is not needed anymore.

Remove TheTVDB from the contributing guide

---

app/src/main/java/com/battlelancer/seriesguide/provider/SgShow2Helper.kt
app/src/main/java/com/battlelancer/seriesguide/ui/stats/StatsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/ui/stats/StatsViewModel.kt
app/src/main/res/layout/fragment_stats.xml
app/src/main/res/values/strings.xml

Relates to #773 
https://github.com/UweTrottmann/SeriesGuide/issues/773#issuecomment-821980582
I'm up for discussion on this statistics enhancement. This can also be solved by joining sg_show, sg_season, and sg_episode tables and extracting more granular information than just relying on the "next episode" info from the stats object.
Also, I added a string key and I don't yet know about the process of translations. For now I marked the string key as non-translatable. This is why this is a draft pull request. New translation will probably be injected by the translation tool. I'd like to ask for help on this part.

Statistics for shows I've finished watching

---

app/src/main/java/com/battlelancer/seriesguide/backend/HexagonAuthError.kt
app/src/main/java/com/battlelancer/seriesguide/backend/HexagonTools.kt
app/src/main/java/com/battlelancer/seriesguide/backend/RemoveCloudAccountDialogFragment.kt
app/src/main/java/com/battlelancer/seriesguide/util/Errors.kt
app/src/test/java/com/battlelancer/seriesguide/backend/HexagonAuthErrorTest.kt

Follow-up to #856 to actually not report sign-in required errors.
Also simplified auth error builder by passing the actual cause directly (so it doesn't need to know about how the Tasks API wraps these).

Cloud: fix detection of sign in errors, get Tasks API cause directly.

---

CHANGELOG.md
app/src/main/java/com/battlelancer/seriesguide/notifications/NotificationService.kt
app/src/main/java/com/battlelancer/seriesguide/sync/AccountUtils.java
app/src/main/java/com/battlelancer/seriesguide/sync/SgSyncAdapter.kt
app/src/test/java/com/battlelancer/seriesguide/notifications/NotificationServiceTest.kt

- Do not crash if permission to set alarms and reminders has been removed, schedule inexact episode notifications instead. #843
- Re-calculate wake-up time if next to notify about episode has been removed/time has changed/show notifications were disabled.

Handle missing SCHEDULE_EXACT_ALARM permission, improve notification service wake-up alarms

---

app/src/main/java/com/battlelancer/seriesguide/jobs/BaseNetworkJob.kt
app/src/main/java/com/battlelancer/seriesguide/jobs/TraktEpisodeJob.kt
app/src/main/java/com/battlelancer/seriesguide/jobs/TraktMovieJob.kt

#839 
If history entries are added based on user actions (e.g. this does not affect the initial data merge when syncing with Trakt), check the history API if an entry already exists at the `watchedAt` timestamp to be used. This is only a single API call and is expected to have a small, in most cases probably empty, response so overhead should be minimal. Edit: for movies need to look up the Trakt id first, but that likely happened already as part of loading details from Trakt (e.g. response is cached).

Check for existing watched entry in history before sending one

---

app/src/main/java/com/battlelancer/seriesguide/backend/CloudSetupActivity.kt
app/src/main/java/com/battlelancer/seriesguide/billing/BillingActivity.kt
app/src/main/java/com/battlelancer/seriesguide/comments/TraktCommentsActivity.kt
app/src/main/java/com/battlelancer/seriesguide/dataliberation/DataLiberationActivity.kt
app/src/main/java/com/battlelancer/seriesguide/extensions/ExtensionsConfigurationActivity.kt
app/src/main/java/com/battlelancer/seriesguide/history/HistoryActivity.kt
app/src/main/java/com/battlelancer/seriesguide/people/PeopleActivity.kt
app/src/main/java/com/battlelancer/seriesguide/people/PersonActivity.kt
app/src/main/java/com/battlelancer/seriesguide/preferences/AboutActivity.kt
app/src/main/java/com/battlelancer/seriesguide/preferences/PreferencesActivityImpl.kt
app/src/main/java/com/battlelancer/seriesguide/shows/episodes/EpisodesActivity.kt
app/src/main/java/com/battlelancer/seriesguide/shows/search/SearchActivityImpl.kt
app/src/main/java/com/battlelancer/seriesguide/traktapi/BaseOAuthActivity.kt
app/src/main/java/com/battlelancer/seriesguide/traktapi/ConnectTraktActivity.kt
app/src/main/java/com/battlelancer/seriesguide/ui/BaseTopActivity.kt
app/src/main/java/com/battlelancer/seriesguide/ui/FullscreenImageActivity.kt

https://developer.android.com/reference/android/app/Activity#onBackPressed()
https://developer.android.com/guide/navigation/navigation-custom-back
Notable: when adding a callback to the `OnBackPressedDispatcher`, have to explicitly call `finish()` instead of `super.onBackPressed()` previously.

Migrate onBackPressed to OnBackPressedDispatcher

---

app/src/main/java/com/battlelancer/seriesguide/appwidget/ListWidgetPreferenceFragment.kt
app/src/main/java/com/battlelancer/seriesguide/comments/TraktCommentsFragment.java
app/src/main/java/com/battlelancer/seriesguide/extensions/ExtensionsConfigurationFragment.java
app/src/main/java/com/battlelancer/seriesguide/history/StreamFragment.kt
app/src/main/java/com/battlelancer/seriesguide/movies/MoviesBaseFragment.kt
app/src/main/java/com/battlelancer/seriesguide/movies/MoviesDiscoverFragment.java
app/src/main/java/com/battlelancer/seriesguide/movies/MoviesNowFragment.java
app/src/main/java/com/battlelancer/seriesguide/movies/MoviesOptionsMenu.kt
app/src/main/java/com/battlelancer/seriesguide/movies/MoviesWatchedFragment.kt
app/src/main/java/com/battlelancer/seriesguide/movies/details/MovieDetailsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/people/PersonFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/ShowsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/calendar/CalendarFragment2.kt
app/src/main/java/com/battlelancer/seriesguide/shows/episodes/EpisodesFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/history/ShowsNowFragment.java
app/src/main/java/com/battlelancer/seriesguide/shows/overview/SeasonsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/search/discover/ShowsDiscoverFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/search/discover/TraktAddFragment.java
app/src/main/java/com/battlelancer/seriesguide/shows/search/popular/ShowsPopularFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/search/similar/SimilarShowsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/stats/StatsFragment.kt

https://developer.android.com/jetpack/androidx/releases/activity#1.4.0-alpha01
Not touching activities, as they may just override `onOptionsItemSelected` to react to the `android.R.id.home` button press. Also not deprecated, so not sure this should be changed at all.

Migrate setHasOptionsMenu to MenuProvider in fragments

---

CHANGELOG.md
app/src/main/java/com/battlelancer/seriesguide/movies/details/MovieDetailsActivity.kt
app/src/main/java/com/battlelancer/seriesguide/movies/details/MovieDetailsFragment.kt
app/src/main/res/layout-w1024dp/fragment_movie.xml
app/src/main/res/layout-w590dp/fragment_movie.xml
app/src/main/res/layout/activity_movie.xml
app/src/main/res/layout/fragment_movie.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values-v23/themes.xml
app/src/main/res/values/themes.xml

MovieDetailsActivity: draw behind system bars, manually color app bar.

---

CHANGELOG.md
app/src/main/java/com/battlelancer/seriesguide/billing/BillingActivity.kt
app/src/main/java/com/battlelancer/seriesguide/comments/TraktCommentsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/extensions/ExtensionsConfigurationFragment.kt
app/src/main/java/com/battlelancer/seriesguide/movies/details/MovieDetailsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/people/PersonFragment.kt
app/src/main/java/com/battlelancer/seriesguide/preferences/AboutPreferencesFragment.kt
app/src/main/java/com/battlelancer/seriesguide/preferences/MoreOptionsActivity.kt
app/src/main/java/com/battlelancer/seriesguide/shows/FirstRunView.kt
app/src/main/java/com/battlelancer/seriesguide/shows/ShowsActivityImpl.kt
app/src/main/java/com/battlelancer/seriesguide/shows/overview/OverviewFragment.kt
app/src/main/java/com/battlelancer/seriesguide/traktapi/BaseOAuthActivity.kt
app/src/main/java/com/battlelancer/seriesguide/util/Metacritic.kt
app/src/main/java/com/battlelancer/seriesguide/util/ServiceUtils.kt
app/src/main/java/com/battlelancer/seriesguide/util/ViewTools.kt
app/src/main/java/com/battlelancer/seriesguide/util/WebTools.kt

This partially undoes #917. Custom tabs are now only used for app-related websites that should appear as part of the app (e.g. the help page, connecting Trakt, ...).
Through user feedback: having a full browser offers more tools, makes switching back and forth from the app to the browser easier.

Use in-app browser only for websites related to the app.

---

CHANGELOG.md
app/src/main/java/com/battlelancer/seriesguide/shows/tools/AddUpdateShowTools.kt

Will also add this to a bugfix release for version 68.

Custom time: apply corrections if NOT using it on episodes.

---

app/src/main/java/com/battlelancer/seriesguide/lists/ListManageDialogFragment.kt
app/src/main/java/com/battlelancer/seriesguide/movies/search/MoviesSearchActivity.kt
app/src/main/java/com/battlelancer/seriesguide/shows/RemoveShowDialogFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/ShowsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/overview/ShowFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/search/SearchActivityImpl.kt
app/src/main/java/com/battlelancer/seriesguide/shows/search/discover/BaseAddShowsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/traktapi/GenericCheckInDialogFragment.kt
app/src/main/java/com/battlelancer/seriesguide/util/HighlightTools.kt
app/src/main/java/com/battlelancer/seriesguide/util/ShortcutCreator.kt

- https://developer.android.com/jetpack/androidx/releases/lifecycle#2.6.0
- https://issuetracker.google.com/issues/270049505#comment2
The deprecated launchWhen and whenStateAtLeast APIs do suspend and not cancel a running block if state dropped below the initial guaranteed state. If the state is never reached again, this leaves the block suspended (and any resources in use) until the Lifecycle reaches the destroyed state.

Migrate launchWhen and whenStateAtLeast Coroutine helpers

---

app/src/main/java/com/battlelancer/seriesguide/preferences/SgPreferencesFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/ShowsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/ui/BaseTopActivity.kt
build.gradle.kts
gradle/libs.versions.toml

> "overridePendingTransition(int, int) which doesn't work for predictive back"
OK, will not make any changes, it's just for predictive back.

Compile with SDK 34 (Android 14)

---

CHANGELOG.md
app/src/main/java/com/battlelancer/seriesguide/sync/SgSyncAdapter.kt

Quick fix for #953: instead of checking for a pending sync, check if a sync is active. This still should prevent scheduling too many syncs.
Also add some log messages to diagnose.

Android 14: work around sync always marked as pending by the system

---

app/src/main/java/com/battlelancer/seriesguide/movies/details/MovieTrailersLoader.kt
app/src/main/java/com/battlelancer/seriesguide/shows/overview/ShowFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/overview/ShowViewModel.kt
app/src/main/java/com/battlelancer/seriesguide/shows/search/discover/AddShowDialogFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/search/discover/AddShowDialogViewModel.kt
app/src/main/java/com/battlelancer/seriesguide/tmdbapi/TmdbTools2.kt
app/src/main/java/com/battlelancer/seriesguide/util/LanguageTools.kt
app/src/main/res/layout/dialog_addshow.xml
app/src/main/res/layout/fragment_show_narrow.xml
app/src/main/res/layout/fragment_show_regular.xml

Support displaying show trailer

---

app/src/main/java/com/battlelancer/seriesguide/shows/search/discover/AddShowDialogFragment.kt
app/src/main/java/com/battlelancer/seriesguide/streaming/StreamingSearch.kt
app/src/main/res/layout/buttons_episode.xml
app/src/main/res/layout/buttons_movie.xml
app/src/main/res/layout/dialog_addshow.xml
app/src/main/res/layout/fragment_show_narrow.xml
app/src/main/res/layout/fragment_show_regular.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

Also reduce brightness of outline and use non-colored text to avoid them sticking out too much.
Leaving other outlined buttons as is for now.

Layout show buttons in horizontal wrapping chains

---

CHANGELOG.md
app/src/main/java/com/battlelancer/seriesguide/shows/episodes/EpisodePagerAdapter.kt
app/src/main/java/com/battlelancer/seriesguide/shows/episodes/EpisodesActivity.kt
app/src/main/res/layout-w1024dp/activity_episodes.xml
app/src/main/res/layout-w590dp/activity_episodes.xml
app/src/main/res/layout/activity_episodes.xml

ViewPager2 performance is really bad. Doing a quick trace shows the issue is layouts getting inflated a lot. Maybe this can be tweaked by parameters?
- `offscreenPageLimit = 1` improves things a bit, but still not even close to v1 performance.
This experimentally switches the episode pager back to the v1 implementation as the v2 one is not really actively developed despite promises. Were there any issues that warranted switching to v2 (e.g. when the amount of pages changed)?

ViewPager2 performance regressions

---

CHANGELOG.md
app/src/main/java/com/battlelancer/seriesguide/jobs/episodes/BaseEpisodesJob.kt
app/src/main/java/com/battlelancer/seriesguide/jobs/episodes/EpisodeBaseJob.java
app/src/main/java/com/battlelancer/seriesguide/jobs/episodes/EpisodeCollectedJob.kt
app/src/main/java/com/battlelancer/seriesguide/jobs/episodes/EpisodeWatchedJob.kt
app/src/main/java/com/battlelancer/seriesguide/jobs/episodes/EpisodeWatchedUpToJob.kt
app/src/main/java/com/battlelancer/seriesguide/jobs/episodes/JobAction.java
app/src/main/java/com/battlelancer/seriesguide/jobs/episodes/SeasonCollectedJob.kt
app/src/main/java/com/battlelancer/seriesguide/jobs/episodes/SeasonWatchedJob.kt
app/src/main/java/com/battlelancer/seriesguide/jobs/episodes/ShowCollectedJob.kt
app/src/main/java/com/battlelancer/seriesguide/jobs/episodes/ShowWatchedJob.kt
app/src/main/java/com/battlelancer/seriesguide/shows/database/SgEpisode2Helper.kt
app/src/main/java/com/battlelancer/seriesguide/shows/history/SgActivity.kt
app/src/main/java/com/battlelancer/seriesguide/shows/history/SgActivityHelper.kt

Adding with highest number and season first (so exact opposite of how it's sent to Trakt). History view is still restricted to 50 items.
But increased number of days to keep for old entries from 30 to 90.

Local history for multiple episodes

---

CHANGELOG.md
app/src/main/java/com/battlelancer/seriesguide/shows/calendar/CalendarAdapter2.kt
app/src/main/java/com/battlelancer/seriesguide/shows/calendar/CalendarFragment2.kt
app/src/main/java/com/battlelancer/seriesguide/shows/calendar/CalendarFragment2ViewModel.kt
app/src/main/java/com/battlelancer/seriesguide/shows/calendar/CalendarItemViewHolder.kt

At the downside that the RecyclerView will know of all items and therefore the fast scroller is harder to use and will lag quite a bit when jumping far. Though slowly scrolling through items still works as expected.
If that will cause ANRs, think about removing the fast scroller or somehow adding a debounce when scrolling (likely requiring a lot of effort).

Calendar: enable placeholders to not re-set scroll position on refresh

---

app/src/amazon/java/com/battlelancer/seriesguide/billing/amazon/AmazonBillingActivity.kt
app/src/amazon/res/layout/activity_amazon_billing.xml
app/src/amazon/res/values/donottranslate.xml
app/src/main/java/com/battlelancer/seriesguide/backend/CloudSetupFragment.kt
app/src/main/java/com/battlelancer/seriesguide/billing/BillingActivity.kt
app/src/main/java/com/battlelancer/seriesguide/shows/overview/ShowFragment.kt
app/src/main/res/drawable/ic_awesome_black_24dp.xml
app/src/main/res/layout/activity_billing.xml
app/src/main/res/layout/activity_more_options.xml
app/src/main/res/values/donottranslate.xml

Not with this, but: think about introducing a new in-app one-time purchase that does not include Cloud (which has the highest recurring costs).

Sustain future updates

---

CHANGELOG.md
app/proguard-rules.pro
app/src/amazon/AndroidManifest.xml
app/src/amazon/README.md
app/src/main/AndroidManifest.xml
build.gradle.kts

Version 3.0.5 of the Amazon Appstore SDK (`com.amazon.device:amazon-appstore-sdk:3.0.5`) does no longer include ProGuard rules. This breaks app public key verification (`AUTH_TOKEN_VERIFICATION_FAILURE`).
Add them manually again.

Fix Release 2024.3.6 (Amazon only)

---

CHANGELOG.md
app/src/main/java/com/battlelancer/seriesguide/settings/TmdbSettings.kt
app/src/main/java/com/battlelancer/seriesguide/shows/episodes/EpisodeDetailsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/overview/OverviewFragment.kt
app/src/main/java/com/battlelancer/seriesguide/util/ImageTools.kt
app/src/test/java/com/battlelancer/seriesguide/util/ImageToolsTest.kt

The cache server is not using the full cache size, so make use of it.
Also refactor ImageTools a bit to de-duplicate and document code.

Higher resolution episode images

---

CHANGELOG.md
app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/battlelancer/seriesguide/history/UserEpisodeStreamFragment.kt
app/src/main/java/com/battlelancer/seriesguide/history/UserMovieStreamFragment.kt
app/src/main/java/com/battlelancer/seriesguide/lists/SgListFragment.kt
app/src/main/java/com/battlelancer/seriesguide/movies/MovieClickListenerImpl.kt
app/src/main/java/com/battlelancer/seriesguide/movies/MoviesDiscoverFragment.kt
app/src/main/java/com/battlelancer/seriesguide/movies/MoviesHistoryFragment.kt
app/src/main/java/com/battlelancer/seriesguide/movies/details/MovieDetailsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/people/PeopleListHelper.kt
app/src/main/java/com/battlelancer/seriesguide/shows/ShowsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/calendar/CalendarFragment2.kt
app/src/main/java/com/battlelancer/seriesguide/shows/episodes/EpisodeDetailsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/history/ShowsHistoryFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/overview/OverviewFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/overview/SeasonsFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/overview/ShowFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/search/EpisodeSearchFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/search/ShowSearchFragment.kt
app/src/main/java/com/battlelancer/seriesguide/shows/search/discover/ShowsDiscoverFragment.kt
app/src/main/java/com/battlelancer/seriesguide/ui/BaseThemeActivity.kt
app/src/main/java/com/battlelancer/seriesguide/util/ActivityTools.kt
app/src/main/java/com/battlelancer/seriesguide/util/PackageTools.kt
app/src/main/java/com/battlelancer/seriesguide/util/ThemeUtils.kt
app/src/main/java/com/battlelancer/seriesguide/util/Utils.java
build.gradle.kts
gradle/libs.versions.toml

Resolving of Android 15 API deprecations deferred to #1080.

Dependency updates, compile SDK 35, re-enable predictive back

---

CHANGELOG.md
app/src/main/java/com/battlelancer/seriesguide/lists/AddListDialogFragment.kt
app/src/main/java/com/battlelancer/seriesguide/lists/DeleteListDialogFragment.kt
app/src/main/java/com/battlelancer/seriesguide/lists/ListManageDialogFragment.kt
app/src/main/java/com/battlelancer/seriesguide/lists/ListsTools.java
app/src/main/java/com/battlelancer/seriesguide/lists/database/SgListHelper.kt
app/src/main/java/com/battlelancer/seriesguide/util/tasks/DeleteListTask.java
app/src/main/res/layout/dialog_add_list.xml
app/src/main/res/layout/dialog_list_manage.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-cy/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-eo/strings.xml
app/src/main/res/values-gl/strings.xml
app/src/main/res/values-hr/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-in/strings.xml
app/src/main/res/values-iw/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-mk/strings.xml
app/src/main/res/values-nb/strings.xml
app/src/main/res/values-ro/strings.xml
app/src/main/res/values-ta/strings.xml
app/src/main/res/values-th/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

Confirm list deletion
