UweTrottmann/SeriesGuide

CONTRIBUTING.md
`fabric.properties` should be used instead of `crashlytics.properties`
=> Update contribution guildelines

.gitignore, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, CONTRIBUTING.md, api/build.gradle, app/build.gradle
=> Debug builds should just work

app/src/main/java/com/battlelancer/seriesguide/ui/search/AddShowDialogFragment.java, app/src/main/java/com/battlelancer/seriesguide/ui/stats/StatsFragment.java, app/src/main/java/com/battlelancer/seriesguide/util/ClipboardTools.kt, app/src/main/res/layout/dialog_addshow.xml, app/src/main/res/layout/fragment_stats.xml
=> Replace textIsSelectable="true" with long-click to copy to clipboard EVERYWHERE

privacy.html
- Add additional links with more information.
=> Update privacy policy for Google Analytics for Firebase

app/src/main/java/com/battlelancer/seriesguide/ui/shows/FilterShowsView.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/ShowsDistillationFragment.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/ShowsDistillationPageAdapter.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/ShowsDistillationSettings.java, app/src/main/java/com/battlelancer/seriesguide/ui/shows/ShowsFragment.java, app/src/main/java/com/battlelancer/seriesguide/ui/shows/ShowsViewModel.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/SortShowsView.kt, app/src/main/java/com/battlelancer/seriesguide/widgets/WrappingViewPager.kt, app/src/main/res/drawable/sg_distillation_dialog_background.xml, app/src/main/res/layout/dialog_shows_distillation.xml, app/src/main/res/layout/tabstrip_item_allcaps_transparent.xml, app/src/main/res/layout/view_filter_shows.xml, app/src/main/res/layout/view_sort_shows.xml, app/src/main/res/menu/shows_menu.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
=> Move show filter and sort order settings to own dialog

app/src/main/java/com/battlelancer/seriesguide/ui/movies/MovieDetailsFragment.kt, app/src/main/res/values-v23/themes.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/themes.xml
Makes action bar text more readable.
=> Darker overlay status and action bar

app/src/main/java/com/battlelancer/seriesguide/provider/EpisodeHelper.java, app/src/main/java/com/battlelancer/seriesguide/ui/movies/AutoGridLayoutManager.java, app/src/main/java/com/battlelancer/seriesguide/ui/shows/CalendarAdapter2.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/CalendarFragment2.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/CalendarFragment2ViewModel.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/CalendarHeaderViewHolder.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/CalendarItemViewHolder.kt, app/src/main/java/com/battlelancer/seriesguide/util/TimeTools.java, app/src/main/java/com/battlelancer/seriesguide/widgets/FastScrollerDecoration.java, app/src/main/res/drawable/fast_scroll_thumb.xml, app/src/main/res/drawable/fast_scroll_track.xml, app/src/main/res/layout/fragment_calendar2.xml, app/src/main/res/layout/item_calendar.xml, app/src/main/res/values/dimens.xml
=> RecyclerView infinite calendar

app/src/main/java/com/battlelancer/seriesguide/SgApp.kt, app/src/main/java/com/battlelancer/seriesguide/traktapi/TraktSettings.java, app/src/main/java/com/battlelancer/seriesguide/ui/ShowsActivity.java, app/src/main/java/com/battlelancer/seriesguide/ui/movies/MovieTools.java
=> Release 50.1

app/build.gradle, app/src/main/java/com/battlelancer/seriesguide/SgApp.kt, app/src/main/java/com/battlelancer/seriesguide/settings/AppSettings.java, app/src/main/java/com/battlelancer/seriesguide/ui/BaseNavDrawerActivity.java, app/src/main/java/com/battlelancer/seriesguide/ui/DebugViewFragment.kt, app/src/main/java/com/battlelancer/seriesguide/ui/preferences/SgPreferencesFragment.kt, app/src/main/res/values/donottranslate.xml, app/src/main/res/xml/settings_root.xml
=> Add a user debug mode

app/src/main/java/com/battlelancer/seriesguide/ui/overview/OverviewFragment.java, app/src/main/res/layout/fragment_overview.xml
=> OverviewFragment: add empty view, suggest to look for similar shows.

CONTRIBUTING.md
Fixed the link to the community site in the contribution file
=> Fixed Discussion link

app/src/androidTest/java/com/battlelancer/seriesguide/sync/TmdbSyncTest.java, app/src/androidTest/java/com/battlelancer/seriesguide/sync/TvdbSyncTest.java, app/src/main/java/com/battlelancer/seriesguide/sync/SgSyncAdapter.java, app/src/main/java/com/battlelancer/seriesguide/sync/SyncProgress.java, app/src/main/java/com/battlelancer/seriesguide/sync/TmdbSync.kt, app/src/main/java/com/battlelancer/seriesguide/sync/TvdbSync.java, app/src/main/java/com/battlelancer/seriesguide/widgets/SyncStatusView.java
They are in English and only mention the TVDB/TMDB ID of the failed show or movie. But let's start easy.
=> Show last show or movie error if syncing fails

app/src/main/java/com/battlelancer/seriesguide/provider/MovieHelper.java, app/src/main/java/com/battlelancer/seriesguide/provider/ShowHelper.java, app/src/main/java/com/battlelancer/seriesguide/sync/TmdbSync.kt, app/src/main/java/com/battlelancer/seriesguide/sync/TvdbSync.java
Follow-up to
Display first show or movie update failure in SyncStatusView. Uwe Trottmann 12.03.2020 08:37
=> Follow-up: also print title of show/movie that failed to update.

app/build.gradle, app/src/main/java/com/battlelancer/seriesguide/SgBackupAgent.kt, app/src/main/java/com/battlelancer/seriesguide/dataliberation/BackupSettings.java, app/src/main/java/com/battlelancer/seriesguide/streaming/StreamingSearch.kt, app/src/main/java/com/battlelancer/seriesguide/sync/HexagonMovieSync.kt, app/src/main/java/com/battlelancer/seriesguide/ui/episodes/EpisodesActivity.kt, app/src/main/java/com/battlelancer/seriesguide/ui/episodes/EpisodesFragment.kt, app/src/main/java/com/battlelancer/seriesguide/ui/movies/MoviesOptionsMenu.kt, app/src/main/java/com/battlelancer/seriesguide/ui/overview/SeasonsFragment.kt, app/src/main/java/com/battlelancer/seriesguide/ui/preferences/SgPreferencesFragment.kt, app/src/main/java/com/battlelancer/seriesguide/ui/search/ShowsDiscoverFragment.kt, app/src/main/java/com/battlelancer/seriesguide/ui/search/SimilarShowsActivity.kt, app/src/main/java/com/battlelancer/seriesguide/ui/search/TvdbIdExtractor.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/CalendarFragment2.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/CalendarSettings.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/FirstRunView.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/ShowsDistillationFragment.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/ShowsDistillationSettings.kt, app/src/main/java/com/battlelancer/seriesguide/ui/stats/StatsFragment.kt, app/src/main/java/com/battlelancer/seriesguide/util/ClipboardTools.kt, app/src/test/resources/robolectric.properties, build.gradle
=> Compile with and target Android SDK 29 (Q)

app/build.gradle, app/src/main/java/com/battlelancer/seriesguide/thetvdbapi/TvdbEpisodeTools.kt, build.gradle, tmdb-api/build.gradle
Closes #727 
If TheTVDB returns HTTP 404 there are no episodes. So instead of aborting, add/update the show.
Tested using https://thetvdb.com/series/dear.
=> Support adding/updating shows without episodes

CHANGELOG.md, app/src/main/java/com/battlelancer/seriesguide/ui/shows/ShowsViewModel.kt, build.gradle
=> Seriesguide 56

CHANGELOG.md, app/src/main/java/com/battlelancer/seriesguide/provider/SgEpisode2Helper.kt, app/src/main/java/com/battlelancer/seriesguide/ui/shows/ShowTools2.kt, build.gradle
* 🔧 Update episodes not found on TMDb if they get added to TMDb at some later point, if the number matches.
=> SeriesGuide 58.1

CHANGELOG.md, app/src/main/java/com/battlelancer/seriesguide/provider/SgSeason2Helper.kt, app/src/main/java/com/battlelancer/seriesguide/ui/lists/ListItemsAdapter.java, app/src/main/java/com/battlelancer/seriesguide/ui/shows/TraktRecentEpisodeHistoryLoader.java, build.gradle
* 🔧 Display details for legacy season and episode list items.
* 🔨 Display any recently watched show from Trakt in history tab.
=> SeriesGuide 58.2

CHANGELOG.md, app/src/main/java/com/battlelancer/seriesguide/sync/SgSyncAdapter.java, app/src/main/java/com/battlelancer/seriesguide/ui/lists/ListsTools2.kt, build.gradle
* 🔨 Fix issues when migrating list items that would prevent Cloud sync to succeed.
=> SeriesGuide 58.3

CHANGELOG.md, app/src/main/java/com/battlelancer/seriesguide/dataliberation/JsonImportTask.java, app/src/main/java/com/battlelancer/seriesguide/provider/SeriesGuideContract.java, app/src/main/java/com/battlelancer/seriesguide/ui/lists/ListsTools2.kt, build.gradle
* 🔨 Fix issues when migrating list items that would prevent Cloud sync to succeed.
* 🔧 Ensure valid list item IDs when importing.
* 🔧 Import legacy season and episode list items again. If restored together with an old shows backup, those can still be displayed.
=> SeriesGuide 58.4

CHANGELOG.md, app/src/main/java/com/battlelancer/seriesguide/provider/SeriesGuideContract.java, build.gradle
* 🔨 Do not crash when generating list item IDs.
=> SeriesGuide 58.5

app/src/main/AndroidManifest.xml, app/src/main/java/com/battlelancer/seriesguide/appwidget/ListWidgetProvider.kt, app/src/main/java/com/battlelancer/seriesguide/billing/BillingActivity.kt, app/src/main/java/com/battlelancer/seriesguide/jobs/BaseNetworkEpisodeJob.kt, app/src/main/java/com/battlelancer/seriesguide/jobs/BaseNetworkMovieJob.kt, app/src/main/java/com/battlelancer/seriesguide/service/NotificationAlarmReceiver.kt, app/src/main/java/com/battlelancer/seriesguide/service/NotificationService.kt, app/src/main/java/com/battlelancer/seriesguide/traktapi/TraktCredentials.kt, app/src/main/java/com/battlelancer/seriesguide/util/AppUpgrade.kt, app/src/main/java/com/battlelancer/seriesguide/util/PendingIntentCompat.kt, build.gradle.kts
https://developer.android.com/about/versions/12/behavior-changes-12
- PendingIntent mutability flags https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent
- Permission for exact alarms (e.g. `NotificationService`) https://developer.android.com/about/versions/12/behavior-changes-12#exact-alarm-permission
=> Android 12

app/src/main/java/com/battlelancer/seriesguide/backend/CloudSetupFragment.kt, app/src/main/java/com/battlelancer/seriesguide/backend/HexagonAuthError.kt, app/src/main/java/com/battlelancer/seriesguide/backend/HexagonTools.kt, app/src/main/java/com/battlelancer/seriesguide/backend/RemoveCloudAccountDialogFragment.kt, app/src/main/java/com/battlelancer/seriesguide/util/Errors.kt
Also report status codes as separate field for auth errors for easier filtering.
=> Do not report sign in required errors

app/src/main/java/com/battlelancer/seriesguide/sync/TraktEpisodeSync.kt, app/src/main/java/com/battlelancer/seriesguide/sync/TraktMovieSync.kt, app/src/main/java/com/battlelancer/seriesguide/sync/TraktRatingsSync.kt, app/src/main/java/com/battlelancer/seriesguide/sync/TraktSync.kt, app/src/main/res/values/strings.xml
=> Trakt Sync: show specific error if watchlist is full

CHANGELOG.md, app/src/androidTest/java/com/battlelancer/seriesguide/shows/tools/CustomReleaseTimeTest.kt, app/src/main/java/com/battlelancer/seriesguide/shows/overview/CustomReleaseTimeDialogFragment.kt, app/src/main/java/com/battlelancer/seriesguide/shows/overview/CustomReleaseTimeDialogModel.kt, app/src/main/java/com/battlelancer/seriesguide/util/TimeTools.kt, app/src/main/res/layout/dialog_custom_release_time.xml
=> Fix custom time reset

CHANGELOG.md, app/src/main/java/com/battlelancer/seriesguide/shows/tools/AddUpdateShowTools.kt, build.gradle.kts
Cherry picks #938 to release 68.
=> Release 68.0.6

app/build.gradle.kts, app/src/main/java/com/battlelancer/seriesguide/provider/SgRoomDatabase.kt, billing/build.gradle.kts, gradle/libs.versions.toml
- ~kapt [target JVM issue](https://youtrack.jetbrains.com/issue/KT-55947/Unable-to-set-kapt-jvm-target-version) appears to be resolved by fixing a [related issue](https://youtrack.jetbrains.com/issue/KT-58745)~
- Room or kapt is broken: fixed by updating Room.
=> Update Kotlin to 1.9

CHANGELOG.md, app/src/main/java/com/battlelancer/seriesguide/comments/TraktCommentsFragment.kt, app/src/main/java/com/battlelancer/seriesguide/comments/TraktCommentsLoader.kt, app/src/main/java/com/battlelancer/seriesguide/comments/TraktCommentsViewModel.kt, app/src/main/java/com/battlelancer/seriesguide/traktapi/SgTrakt.kt, app/src/main/java/com/battlelancer/seriesguide/traktapi/TraktComments.kt, app/src/main/java/com/battlelancer/seriesguide/traktapi/TraktTask.java, gradle/libs.versions.toml, settings.gradle.kts
=> Trakt comments: make refresh skip cache to get latest comments

CHANGELOG.md, app/src/main/java/com/battlelancer/seriesguide/people/PeopleListHelper.kt, app/src/main/java/com/battlelancer/seriesguide/tmdbapi/TmdbTools2.kt
Also display all of those of interest in the overview of a show/movie.
=> Crew: display creators or directors/writers first, then by job title

CHANGELOG.md, app/build.gradle.kts, app/src/androidTest/java/com/battlelancer/seriesguide/modules/TestHttpClientModule.kt, app/src/main/java/com/battlelancer/seriesguide/SgApp.kt, app/src/main/java/com/battlelancer/seriesguide/comments/TraktCommentsAdapter.kt, app/src/main/java/com/battlelancer/seriesguide/modules/HttpClientModule.kt, app/src/main/java/com/battlelancer/seriesguide/people/PeopleAdapter.kt, app/src/main/java/com/battlelancer/seriesguide/people/PeopleListHelper.kt, app/src/main/java/com/battlelancer/seriesguide/tmdbapi/TmdbTools.kt, gradle/libs.versions.toml
=> Fix image loading on Android 7 and older

CHANGELOG.md, app/src/main/AndroidManifest.xml, app/src/main/java/com/battlelancer/seriesguide/preferences/PreferencesActivityImpl.kt, app/src/main/java/com/battlelancer/seriesguide/shows/ShowsFragment.kt, app/src/main/java/com/battlelancer/seriesguide/shows/episodes/EpisodesActivity.kt, app/src/main/java/com/battlelancer/seriesguide/ui/BaseTopActivity.kt
- https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture
- https://developer.android.com/guide/navigation/navigation-custom-back
- https://stackoverflow.com/a/78417313/1000543
=> Android 15: support predictive back

CHANGELOG.md, app/src/main/java/com/battlelancer/seriesguide/billing/BillingActivity.kt, app/src/main/java/com/battlelancer/seriesguide/shows/ShowsActivityImpl.kt, app/src/main/java/com/battlelancer/seriesguide/shows/ShowsFragment.kt, app/src/main/java/com/battlelancer/seriesguide/shows/overview/ShowFragment.kt, app/src/main/java/com/battlelancer/seriesguide/ui/BaseMessageActivity.kt, app/src/main/java/com/battlelancer/seriesguide/ui/BaseTopActivity.kt, app/src/main/java/com/battlelancer/seriesguide/util/SupportTheDev.kt
Resolves issue from #887 thanks to a suggestion from someone else: https://github.com/material-components/material-components-android/issues/3446#issuecomment-2537553207
=> Align snackbars correctly to bottom nav bar

CHANGELOG.md, app/src/main/java/com/battlelancer/seriesguide/appwidget/ListWidgetProvider.kt, app/src/main/java/com/battlelancer/seriesguide/appwidget/ListWidgetRemoteViewsFactory.kt, build.gradle.kts
[#1118](https://github.com/UweTrottmann/SeriesGuide/issues/1118)
=> Fix Release 2025.2.11
